// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { ICompareString, javascript } from 'projen';

/**
 * EslintOptions
 */
export interface EslintOptions {
  /**
   * Write eslint configuration as YAML instead of JSON.
   * @default false
   * @stability experimental
   */
  readonly yaml?: boolean;
  /**
   * Path to `tsconfig.json` which should be used by eslint.
   * @default "./tsconfig.json"
   * @stability experimental
   */
  readonly tsconfigPath?: string;
  /**
   * Always try to resolve types under `<root>@types` directory even it doesn't contain any source code.
   * This prevents `import/no-unresolved` eslint errors when importing a `@types/*` module that would otherwise remain unresolved.
   * @default true
   * @stability experimental
   */
  readonly tsAlwaysTryTypes?: boolean;
  /**
   * The extends array in eslint is order dependent.
   * This option allows to sort the extends array in any way seen fit.
   * @default - Use known ESLint best practices to place "prettier" plugins at the end of the array
   * @stability experimental
   */
  readonly sortExtends?: ICompareString;
  /**
   * Enable prettier for code formatting.
   * @default true
   * @stability experimental
   */
  readonly prettier?: boolean;
  /**
   * Projenrc file to lint.
   * Use empty string to disable.
   * @default "projenrc.js"
   * @deprecated provide as `devdirs`
   * @stability deprecated
   */
  readonly lintProjenRcFile?: string;
  /**
   * Should we lint .projenrc.js.
   * @default true
   * @deprecated set to `false` to remove any automatic rules and add manually
   * @stability deprecated
   */
  readonly lintProjenRc?: boolean;
  /**
   * List of file patterns that should not be linted, using the same syntax as .gitignore patterns.
   * @default [ '*.js', '*.d.ts', 'node_modules/', '*.generated.ts', 'coverage' ]
   * @stability experimental
   */
  readonly ignorePatterns?: Array<string>;
  /**
   * File types that should be linted (e.g. [ ".js", ".ts" ]).
   * @default [".ts"]
   * @stability experimental
   */
  readonly fileExtensions?: Array<string>;
  /**
   * Files or glob patterns or directories with source files that include tests and build tools.
   * These sources are linted but may also import packages from `devDependencies`.
   * @default []
   * @stability experimental
   */
  readonly devdirs?: Array<string>;
  /**
   * Options for eslint command executed by eslint task.
   * @stability experimental
   */
  readonly commandOptions?: javascript.EslintCommandOptions;
  /**
   * Enable import alias for module paths.
   * @default undefined
   * @stability experimental
   */
  readonly aliasMap?: Record<string, string>;
  /**
   * Enable import alias for module paths.
   * @default undefined
   * @stability experimental
   */
  readonly aliasExtensions?: Array<string>;
  /**
   * Files or glob patterns or directories with source files to lint (e.g. [ "src" ]).
   * @default src
   * @stability experimental
   */
  readonly dirs: Array<string>;
}
