// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { PulumiEscSetup } from '../../';

/**
 * GithubCredentialsPersonalAccessTokenOptions
 */
export interface GithubCredentialsPersonalAccessTokenOptions {
  /**
   * @stability experimental
   */
  readonly secret?: string;
  /**
   * Optionally include setup steps and resolve app credentials from Pulumi ESC outputs
   * @default do not include pulumi esc setup
   */
  readonly pulumiEscSetup?: PulumiEscSetup;
}
