// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { github } from 'projen';
import type { PulumiEscSetup } from '../../';

/**
 * GithubCredentialsAppOptions
 */
export interface GithubCredentialsAppOptions {
  /**
   * List of repositories to grant access to.
   * @default - if owner is set and repositories is empty, access will be scoped to all repositories in the provided repository owner's installation.
If owner and repositories are empty, access will be scoped to only the current repository.
   * @stability experimental
   */
  readonly repositories?: Array<string>;
  /**
   * The secret containing the GitHub App private key.
   * Escaped newlines (\\n) will be automatically replaced with actual newlines.
   * When `pulumiEscSetup` is provided, this value is used as the ESC output key.
   * @default PROJEN_APP_PRIVATE_KEY
   * @stability experimental
   */
  readonly privateKeySecret?: string;
  /**
   * The permissions granted to the token.
   * @default - all permissions granted to the app
   * @stability experimental
   */
  readonly permissions?: github.workflows.AppPermissions;
  /**
   * The owner of the GitHub App installation.
   * @default - if empty, defaults to the current repository owner
   * @stability experimental
   */
  readonly owner?: string;
  /**
   * Optionally include setup steps and resolve app credentials from Pulumi ESC outputs
   * @default do not include pulumi esc setup
   */
  readonly pulumiEscSetup?: PulumiEscSetup;
  /**
   * The name of the secret that contains the app client id.
   * When `pulumiEscSetup` is provided, this value is used as the ESC output key.
   * @default PROJEN_APP_CLIENT_ID
   */
  readonly clientIdSecret?: string;
}
