// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { github } from 'projen';
import type { PulumiEscSetup } from '../../';

/**
 * GithubCredentialsAppOptions
 */
export interface GithubCredentialsAppOptions {
  /**
   * @default PROJEN_APP_PRIVATE_KEY
   * @stability experimental
   */
  readonly privateKeySecret?: string;
  /**
   * The permissions granted to the token.
   * @default - all permissions granted to the app
   * @stability experimental
   */
  readonly permissions?: github.workflows.AppPermissions;
  /**
   * Optionally include setup steps to inject environment variables from Pulumi ESC
   * @default do not include pulumi esc setup
   */
  readonly pulumiEscSetup?: PulumiEscSetup;
  /**
   * The name of the secret that contains the app client id
   * @default PROJEN_APP_CLIENT_ID
   */
  readonly clientIdSecret?: string;
}
