// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { PrettierSettings } from '../../';
import type { IgnoreFileOptions, javascript } from 'projen';

/**
 * PrettierOptions
 */
export interface PrettierOptions {
  /**
   * Write prettier configuration as YAML instead of JSON.
   * @default false
   * @stability experimental
   */
  readonly yaml?: boolean;
  /**
   * Prettier settings.
   * @default - default settings
   * @stability experimental
   */
  readonly settings?: PrettierSettings;
  /**
   * Provide a list of patterns to override prettier configuration.
   * @default []
   * @stability experimental
   */
  readonly overrides?: Array<javascript.PrettierOverride>;
  /**
   * Configuration options for .prettierignore file.
   * @stability experimental
   */
  readonly ignoreFileOptions?: IgnoreFileOptions;
  /**
   * Defines an .prettierIgnore file.
   * @default true
   * @stability experimental
   */
  readonly ignoreFile?: boolean;
}
