// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import type { PulumiPluginOptions } from '../../';

/**
 * PulumiTypeScriptOptions
 */
export interface PulumiTypeScriptOptions {
  /**
   * The pulumi version to use. Setting this will mean that projen will manage the Pulumi version going forward
   * @default *
   */
  readonly pulumiVersion?: string;
  /**
   * Option for the PulumiPlugin.yaml file
   */
  readonly pluginOptions?: PulumiPluginOptions;
}
