// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".

/**
 * PulumiPythonOptions
 */
export interface PulumiPythonOptions {
  /**
   * The pulumi version to use. The version range should be valid semver
   * @default >=3.153 <4.0
   */
  readonly pulumiVersion?: string;
}
